# App Name
name: foodifi

# App Description
description: A Food Wallpapers app.

# App Version for both Android & iOS
version: 1.0.0+1

# Dart SDK Version
environment:
  sdk: ">=2.2.0 <3.0.0"

# App Packages from pub.dev for both debug & release mode & for both Android & iOS
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  sqflite: ^1.2.0
  connectivity: ^0.4.6+2
  rxdart: ^0.22.6
  flutter_spinkit: ^4.1.1+1
  shared_preferences: ^0.5.6+1
  cached_network_image: ^2.0.0
  package_info: ^0.4.0+13
  splashscreen: ^1.2.0
  introduction_screen: ^1.0.7
  # flutter_custom_clippers: ^1.1.0
  # polygon_clipper: ^1.0.2
  quick_actions: ^0.4.0+1
  wave: ^0.0.8
  firebase_performance: ^0.3.1+5
  cloud_firestore: ^0.13.2+3
  firebase_auth: ^0.15.4
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3
  google_sign_in: ^4.1.1
  url_launcher:
  flutter_rating_bar:
  intl:

# App Packages from pub.dev only for debug mode for both Android & iOS
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  http:
  test: any
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  # Assets
  assets:
    - assets/
    - assets/images/

  # Fonts
  fonts:
    - family: foodifi
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
